spring:
  application:
    name: sgu-admission-system
  main:
    headless: false
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.MySQLDialect}
    show-sql: ${DB_SHOW_SQL:false}
